### ISSUE TITLE
Adding a new zone won't trigger jump start

### ISSUE THREAD

**Issue by fagiani** [bAndie91/cloudflare-cli#10]
Hello @bAndie91

I've tried using `cloudflare add zone mydomain.com` and that won't trigger the DNS discovery process as listed on the [API docs](https://api.cloudflare.com/#zone-create-a-zone). I've opened a support ticket on CloudFlare to understand how come the default value is `true` and it is not working unless its present on the request payload.

Regardless of this issue with their documentation, I'd like to understand if having the `jump_start` parameter as part of the `add zone` command is something desired and I can work on a PR for that.

In that case, I'd like only to make sure I get the implementation approach correctly because the only way I was able to get it working was changing this line:

    call_cf_v4 POST /zones name="$1" -- .result '&<"status: $status"'

to this:

    call_cf_v4 POST /zones "{\"name\":\"$1\",\"jump_start\":$2}" -- .result '&<"status: $status"'

Would something like that make sense?

Thanks again!

**Comment by bAndie91** [comment]
I agree, ``"{\"name\":\"$1\",\"jump_start\":true}"`` would work.
