### ISSUE TITLE
end maintaining

### ISSUE THREAD

**Issue by bAndie91** [bAndie91/cloudflare-cli#19]
i don't maintain this project anymore.
feel free to request ownership on this repo, and I'll transfer it to you.

**Comment by jordantrizz** [comment]
I'll take it over, I'll pass it on if I can no longer maintain the project. ⚔

**Comment by bAndie91** [comment]
hi @jordantrizz , thanks for volunteering. 
i tried to transfer but GH did not want to because (1) you already have a repo with the same name and (2) you are already "member of the bAndie91/cloudflare-cli network" after i renamed it. 
i guess you have to delete your repo in order to transfer. rename may not help because GH knows it was forked out from mine.

**Comment by jordantrizz** [comment]
Just transferred the repo into an organization, so it should work now!

**Comment by jordantrizz** [comment]
Thanks @bAndie91 looks good!
