### ISSUE TITLE
Syntax error when adding IP to whitelist

### ISSUE THREAD

**Issue by wojsmol** [bAndie91/cloudflare-cli#2]
Hello
When I add the IP to the whitelist I get the following php error

```
Parse error: syntax error, unexpected T_FUNCTION in Command line code on line 10
(23) Failed writing body
```

Regards

**Comment by bAndie91** [comment]
It seems you use a different PHP version that does not support closure callables.
Which PHP version do you use?
This part of code is not cardinal, so hotfix can be made easily.

**Comment by wojsmol** [comment]
php version: 5.2.17
A good idea would be to add the environment variable allowing to define the path the php cli used by the script.

**Comment by bAndie91** [comment]
> environment variable allowing to define the path the php

it is simply called PATH :-)

btw. see 98a8f335ade2f7eaa00c393ef362e7cde8faaddc

**Comment by wojsmol** [comment]
I mean something like https://github.com/wp-cli/wp-cli/blob/master/bin/wp#L33-L40, so the environment variable to override php from `$PATH`

**Comment by bAndie91** [comment]
run with default php: `cloudflare-cli`
run with php x.y: `PATH=/usr/local/php-x.y/bin:$PATH cloudflare-cli`
run with php z.w: `PATH=/usr/local/php-z.w/bin:$PATH cloudflare-cli`
but you are right in cases when filename of php cli was not `php`.
You might please close the issue if 98a8f33 runs with 5.2.

**Comment by wojsmol** [comment]
[98a8f33](https://github.com/bAndie91/cloudflare-cli/commit/98a8f335ade2f7eaa00c393ef362e7cde8faaddc) runs with 5.2
