### ISSUE TITLE
migrating to APIv4

### ISSUE THREAD

**Issue by bAndie91** [bAndie91/cloudflare-cli#3]
based on https://www.cloudflare.com/migrating-to-v4/
@bAndie91

**Comment by pascalandy** [comment]
Hi! 
Are you still improving this project?

**Comment by bAndie91** [comment]
@pascalandy yes, i am working on it.

**Comment by pascalandy** [comment]
Nice to hear :) I will give it a shoot then!
Cheers

**Comment by bAndie91** [comment]
progress in [branch APIv4](/bAndie91/cloudflare-cli/tree/api-v4)

**Comment by bAndie91** [comment]
done but loosely tested.
