### ISSUE TITLE
Change record issue still exists

### ISSUE THREAD

**Issue by amirbekyan** [bAndie91/cloudflare-cli#8]
Hi

Recently I opened an issue concerning the existing record change. I see you have made some changes but your version still doesn't work. It pushes IP as plain without quots:

<<< curl -X PUT -H Content-Type: application/json --data {"name":"some.domain.name","type":"A","ttl":1,"content":"0.1.4.7","content":0.1.4.7,"proxied":true} https://api.cloudflare.com/client/v4/zones/s0m3z0n3/dns_records/s0m3r3c0rd?page=1&per_page=50

the output is:
E1004: DNS Validation Error
E9041: Invalid proxied mode. Record cannot be proxied
if proxied setting is added in the end of the line, and:
E1004: DNS Validation Error
E9005: Content for A record is invalid. Must be a valid IPv4 address
if not.

command I use:
cloudflare -E my.account@email.addr -T mYT0k3n change record some.domain.name type A content ip.add.re.ss

Regards

**Comment by bAndie91** [comment]
thanks for testing.
feel free to open/reopen ticket if you experience issues.

**Comment by amirbekyan** [comment]
thank you for quick response
Now it works ))
